version: '2'
services:
        mysql:
                build: docker/db
                ports:
                        - "3306:3306"
                env_file: docker/env_file
                volumes:
                        - ./db/init:/docker-entrypoint-initdb.d
                        - mysql_data:/var/lib/mysql
        slapd:
                build: docker/slapd
                env_file: docker/env_file
                ports:
                        - "389:389"
                volumes:
                        - slapd_data:/var/lib/ldap
                        - slapd_conf:/etc/ldap
        tomcat:
                build:
                        context: ./
                        dockerfile: Dockerfile-tomcat
                depends_on:
                        - mysql
                        - slapd
                links:
                        - mysql
                        - slapd
                volumes:
                        - datastore:/opt/ark-datastore
                        - ./tomcat/ark.xml:/usr/local/tomcat/conf/Catalina/localhost/ark.xml
                        - ../ark-container/target/ark.war:/usr/local/tomcat/webapps/ark.war
                env_file: docker/env_file
                ports:
                        - "8080:8080"
                        - "8000:8000"
volumes:
        slapd_data:
        slapd_conf:
        mysql_data:
        datastore:
